import './globals.css'
import { Inter } from 'next/font/google'
import { initVenomConnect } from '../components/venom-connect/configure';
import VenomConnect from 'venom-connect';
import React, { useEffect, useState } from 'react';

const inter = Inter({ subsets: ['latin'] })
const [venomConnect, setVenomConnect] = useState<VenomConnect | undefined>();
  const init = async () => {
    const _venomConnect = await initVenomConnect();
    setVenomConnect(_venomConnect);
  };
  useEffect(() => {
    init();
  }, []);

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className} venomConnect={venomConnect}  >{children}</body>
    </html>
  )
}
